### ISSUE TITLE
support newer gitlab, omnibus install

### ISSUE THREAD

**Issue by JasonBoyles** [rackspace-orchestration-templates/gitlab#15]
This template installs v6.7.3 from github. v7.8.0 is current. 

The official releases of gitlab now recommend the Omnibus installer; this sets up the database, key-value store, etc., and has an extensive [configuration file](https://gitlab.com/gitlab-org/omnibus-gitlab/blob/master/files/gitlab-config-template/gitlab.rb.template) which will let us configure the default login user id and password among other things.

This deployment could be simplified considerably to configure an MTA, [install GitLab via omnibus](https://about.gitlab.com/downloads/), template [the config file](https://gitlab.com/gitlab-org/omnibus-gitlab/blob/master/files/gitlab-config-template/gitlab.rb.template), and trigger reconfiguration (`gitlab-ctl reconfigure`).

**Comment by brint** [comment]
@JasonBoyles has a PR in for this:

https://github.com/rackspace-orchestration-templates/gitlab/pull/17

Waiting for testing to be done across multiple account types.

**Comment by JasonBoyles** [comment]
This is ready to go, @brint & @Linuturk

**Comment by JasonBoyles** [comment]
This closes #17

**Comment by JasonBoyles** [comment]
#17 was merges, thus closing this issue.
